services:
  - type: web
    name: deploy
    env: ruby
    plan: free

    
    buildCommand: |
      bundle install
      bundle exec rails assets:precompile
      bundle exec rails assets:clean
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: deploy-db
          property: connectionString

databases:
  - name: deploy-db
    plan: free
